services:
  app:
    image: haider57/frontend-service:23.10.2024
    build: .
    container_name: frontend
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
    command: serve -s dist -l 4173